export const data = [
    {
        id:48,
        name:'Alice',
        email:'guodenel@war.gf',
        age:11
    },
    {
        id:68,
        name:'Jerry',
        email:'aheokew@obbahose.to',
        age:1
    },
    {
        id:12,
        name:'Connor',
        email:'habuze@sujiho.hm',
        age:9
    },
    {
        id:84,
        name:'Roxie',
        email:'os@odzom.tc',
        age:18
    },
    {
        id:57,
        name:'Jimmy',
        email:'puzreig@pib.sz',
        age:6
    },
    {
        id:69,
        name:'Don',
        email:'wumu@ifged.cg',
        age:14
    },
    {
        id:51,
        name:'Louise',
        email:'vospobga@hu.th',
        age:10
    },
    {
        id:40,
        name:'Helen',
        email:'motdeldac@oh.lr',
        age:16
    },
]